pages/docs/reference/using-maven.md

Marven to Maven

---

pages/docs/tutorials/javascript/getting-started-command-line/command-line-library-js.md

把command-line-library-js.md翻译成简体中文

把command-line-library-js.md翻译成简体中文

---

pages/docs/reference/whatsnew13.md

Translate the 1.3 docs into Chinese.

translate 1.3

---

pages/docs/tutorials/javascript/working-with-modules/working-with-modules.md

Kotlin 与 JavaScript 模块使用 翻译

---

pages/docs/tutorials/coroutines/coroutines-basic-jvm.md

《你的第一个Kotlin协程程序》

---

pages/docs/tutorials/coroutines/async-programming.md

《异步程序设计》小修

---

pages/docs/reference/building-mpp-with-gradle.md

添加 搭建一个多平台项目 翻译

---

pages/docs/reference/code-style-migration-guide.md

**文中的 `style` 均翻译为 `风格` 而非 `样式`**

部分 编码规范 翻译

---

pages/docs/tutorials/native/interop-with-c.md

翻译了一般《与 C 语言库互操作》

---

pages/docs/tutorials/native/interop-with-c.md

《与 C 语言库互操作》翻译完成

---

pages/docs/tutorials/native/mpp-ios-android.md

翻译部分《iOS 与 Android》

---

pages/docs/tutorials/native/mpp-ios-android.md

 将《iOS 与 Android》翻译一半

---

pages/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.md

kotlin-to-javascript.md 翻译完成

---

pages/docs/tutorials/native/mpp-ios-android.md

《iOS 与 Android》翻译完成

---

pages/docs/tutorials/native/mpp-ios-android.md

 校对《iOS 与 Android》

---

pages/docs/tutorials/javascript/getting-started-gradle/getting-started-with-gradle.md
pages/docs/tutorials/javascript/getting-started-idea/getting-started-with-intellij-idea.md

translate getting-started-with-intellij-idea.md(1/2)

---

pages/docs/tutorials/getting-started-eclipse.md

完成 以 Eclipse IDE 入门 翻译

---

pages/docs/tutorials/javascript/getting-started-idea/getting-started-with-intellij-idea.md

translate getting-started-with-intellij-idea.md(2/2)

---

pages/docs/tutorials/getting-started.md

完成 以 IntelliJ IDEA 入门 

---

pages/docs/tutorials/koans.md

翻译 《Kotlin 心印》

---

pages/docs/tutorials/javascript/getting-started-command-line/command-line-library-js.md

校对 command-line-library-js.md

---

pages/docs/tutorials/build-tools.md

翻译 《使用构建工具》

---

pages/docs/tutorials/command-line.md

翻译 《使用命令行编译器》

---

pages/docs/tutorials/command-line.md

完成使用命令行编译器翻译

---

pages/docs/tutorials/native/basic-kotlin-native-app.md

 翻译一段《基本 Kotlin/Native 应用程序》

---

pages/docs/tutorials/native/basic-kotlin-native-app.md

<基本 Kotlin Native 应用程序>翻译一段

---

pages/docs/tutorials/native/basic-kotlin-native-app.md

《基本 Kotlin/Native 应用程序》翻译完成

---

pages/docs/tutorials/native/basic-kotlin-native-app.md

《基本 Kotlin/Native 应用程序》校对

---

pages/docs/tutorials/native/dynamic-libraries.md

《Kotlin/Native 开发动态库》翻译了开头

---

pages/docs/reference/constructing-collections.md

翻译 参考-集合-构造集合

---

pages/docs/tutorials/native/dynamic-libraries.md

 《Kotlin/Native 开发动态库》翻译一段

---

pages/docs/tutorials/native/dynamic-libraries.md

 《Kotlin/Native 开发动态库》翻译完毕

---

pages/docs/tutorials/multiplatform-library.md
pages/docs/tutorials/native/mpp-ios-android.md

增加两处漏翻的补充翻译

---

pages-includes/docs/tutorials/native/lets-create-gradle-build.md

 翻译《KN 开发动态库》一文中的 include 部分

---

pages/docs/tutorials/native/mapping-primitive-data-types-from-c.md

 将“联合”翻译为“联合体”

---

pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

《映射 C 的结构体与联合体》翻译一部分

---

pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

 《映射 C 结构与联合类型》翻译完成

---

pages/docs/tutorials/native/mapping-function-pointers-from-c.md
pages/docs/tutorials/native/mapping-primitive-data-types-from-c.md
pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

《映射 C 函数》翻译完成

---

pages/docs/tutorials/native/mapping-function-pointers-from-c.md
pages/docs/tutorials/native/mapping-primitive-data-types-from-c.md
pages/docs/tutorials/native/mapping-strings-from-c.md
pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

《映射 C 字符串》翻译完毕

---

pages/docs/tutorials/native/apple-framework.md

翻译《Apple Framework》

---

pages/docs/tutorials/native/mpp-ios-android.md

Native 部分文档更新补充翻译完成

---

pages/docs/tutorials/native/mpp-ios-android.md

补充翻译 Native 教程中未翻译的代码注释

---

pages/docs/tutorials/android-frameworks.md

《Android 框架》补充翻译

---

pages/docs/tutorials/kotlin-android.md
pages/docs/tutorials/mixing-java-kotlin-intellij.md

Add translation for 'kotlin-android' and 'mixing-java-kotlin-intellij'

---

pages-includes/docs/tutorials/native/apple-framework-link.md
pages-includes/docs/tutorials/native/basic-kotlin-native-app-codeblocks-link.md
pages-includes/docs/tutorials/native/dynamic-library-link.md
pages-includes/docs/tutorials/native/lets-create-gradle-build.md
pages-includes/docs/tutorials/native/mapping-primitive-data-types-from-c-link.md
pages/docs/tutorials/native/dynamic-libraries.md
pages/docs/tutorials/native/mapping-function-pointers-from-c.md
pages/docs/tutorials/native/mapping-struct-union-types-from-c.md

Native 教程小修

---

pages/docs/tutorials/android-plugin.md

添加 kotlin Android 扩展翻译

---

pages/docs/reference/map-operations.md

Map的相关操作 - 取键与值

---

pages/docs/reference/list-operations.md
pages/docs/reference/map-operations.md
pages/docs/reference/set-operations.md

[翻译完毕！]集合-Map 相关操作

---

pages/docs/reference/ranges.md

集合 - 区间与数列

---

pages/docs/reference/ranges.md

[翻译完毕！]集合 - 区间与数列

---

pages/docs/reference/index.md

Update Kotlin tutorial to new edition(based on v1.3.50).

---

pages/docs/reference/collection-operations.md
pages/docs/reference/collection-transformations.md

 [翻译完毕！] 集合 - 集合操作概述；集合 - 集合转换

---

pages/docs/tutorials/android-plugin.md

翻译-Kotlin Android 扩展-启用实验功能

---

pages/docs/reference/collection-write.md

翻译集合写操作-删除第一小段

---

pages/docs/reference/collection-transformations.md

集合 - 转换 - 打平

---

pages/docs/reference/collection-parts.md

集合 - 取集合的一部分

---

pages/docs/tutorials/quick-run.md

[翻译完毕！] 教程 - 开始 - 运行代码片段

---

pages/docs/tutorials/javascript/debugging-javascript/debugging-javascript.md

[翻译完毕！] 教程 - JavaScript  - 在浏览器中调试Kotlin

---

pages/docs/tutorials/native/using-gradle.md

[翻译完毕！] 教程 - 原生 - 使用Gradle的HelloKotlin/Native

---

pages/docs/tutorials/native/using-intellij-idea.md

[请求合并]使用IntelliJ IDEA的Hello Kotlin / Native

---

pages/docs/reference/basic-syntax.md

[翻译完毕！] 语言指南 - 开始 - 基本语法

---

pages/docs/reference/kapt.md

[翻译完毕！] 语言指南 - 工具 - 使用Kapt

---

pages/docs/reference/code-style-migration-guide.md

[翻译完毕！] 语言指南 - 工具 - 代码风格迁移指南

---

pages/docs/reference/building-mpp-with-gradle.md

翻译 JVM 目标平台中的 Java 支持

---

pages/docs/reference/building-mpp-with-gradle.md

翻译 Android 支持

---

pages/docs/tutorials/command-line.md

添加对 Chocolaty 部分的翻译

---

pages/docs/reference/opt-in-requirements.md

[请求合并...] 语言指南 - 更多语言结构 - Opt-in Requirements 

---

pages/docs/reference/building-mpp-with-gradle.md

翻译 构建通用 framework

---

pages/docs/reference/building-mpp-with-gradle.md

翻译 C 互操作支持

---

pages/docs/reference/mpp-dsl-reference.md

 翻译 Kotlin 多平台 Gradle DSL 参考

---

pages/docs/tutorials/getting-started.md

更改排版，修复加粗字体未加粗 - 开始 - 以 IntelliJ IDEA 入门

---

pages/docs/tutorials/command-line.md
pages/docs/tutorials/getting-started.md

[翻译完毕！] 教程 - 开始 - Kotlin入门

---

pages/docs/reference/server-overview.md

[翻译完毕！] 语言指南 - 概述 - Kotlin 用于服务器端开发

---

pages/docs/reference/building-mpp-with-gradle.md

[翻译完毕！] 语言指南 - 多平台程序设计 - 以Gradle构建

---

pages/docs/reference/native-overview.md

fix double "https://"

---

templates/pages/community.html

[翻译完毕！] 社区 - 概述

---

pages/user-groups/user-group-list.md
templates/groups.html

[翻译完毕！] 社区 - 用户群组

---

pages/community/events.md
templates/community.html

[翻译完毕！] 社区 - 活动 - Kotlin活动

---

pages/community/kotlin-nights/guidelines.md

[翻译完毕！] 社区 - 活动 - 准则与支持

---

pages/community/kotlin-nights/guidelines.md
pages/community/talks.md

[翻译完毕！] 社区 - 会谈与演讲者

---

pages/community/kotlin-nights/branding.md

[翻译完毕！] 社区 - 活动 - 品牌宣传资料

---

pages/docs/tutorials/edu-tools-learner.md

[翻译完毕！] 教程 - 教学 - 通过EduTools插件学习Kotlin

---

pages/docs/tutorials/edu-tools-educator.md

[翻译完毕！] 教程 - 教学 - 通过EduTools插件讲授Kotlin

---

pages/docs/tutorials/httpservlets.md

[翻译完毕！] 教程 - Web开发 - 用 Http Servlets 创建 web 应用

---

templates/pages/education/index.html

[翻译完毕！] 教学 - 概述

---

pages/docs/reference/native-overview.md

[翻译完毕！] 语言指南 - 概述 - Kotlin用于原生开发

---

pages/docs/reference/nested-classes.md

[翻译完毕！] 语言指南 - 类与对象 - 嵌套类

---

pages/docs/reference/js-project-setup.md

[翻译完毕！] 语言指南 - JavaScript - 搭建项目

---

pages/docs/reference/js-interop.md

[翻译完毕！] 语言指南 - JavaScript - Kotlin中调用JavaScript

---

pages/docs/reference/dynamic-type.md

[翻译完毕！] 语言指南 - JavaScript - 动态类型

---

pages/docs/reference/js-to-kotlin-interop.md

[翻译完毕！] 语言指南 - JavaScript - JavaScript中调用Kotlin

---

pages/docs/reference/javascript-dce.md

[翻译完毕！] 语言指南 - JavaScript - JavaScriptDCE

---

pages/docs/reference/comparison-to-java.md

typo fix: 型变

---

pages/docs/reference/classes.md

[翻译完毕！] 语言指南 - 类与对象 - 类与继承

---

pages/docs/reference/mpp-create-lib.md

[翻译完毕！] 语言指南 - 多平台程序设计 - 创建多平台库

---

pages/docs/reference/mpp-discover-project.md

[翻译完毕！] 语言指南 - 多平台程序设计 - 了解项目

---

pages/docs/reference/js-ir-compiler.md

[翻译完毕！] 语言指南 - JavaScript - IR编译器

---

docs/topics/kotlin-brand-assets.md

[翻译完毕！] Kotlin 品牌素材
